### ISSUE TITLE
sub-page change-over rate

### ISSUE THREAD

**Issue by shungerz** [ali1234/pyteletext#1]
With this teletext inserter into raspi-teletext is it possible to change rate in which the sub-pages are display (i.e. 20 seconds instead of 7).
edit:
ok - I think it's the value of the control parameter .... but I'm not sure.

**Comment by peterkvt80** [comment]
The 'control' parameter seems to be providing the control bits that are found in headers. I don't see any timing control. Looking at main.py, I'd say that it is moving to the next carousel page each time that it has done a complete cycle of pages in a magazine. If this is correct then you can slow your carousels down by adding more pages to the magazine. This is a cheap hack. I don't know python but it shouldn't take much work to implement proper page timing.

**Comment by ali1234** [comment]
That is correct. To make each subpage display for longer just add more pages.

**Comment by shungerz** [comment]
Thanks guys.
